"""
PAR (Preliminary Assessment Report) Model

Represents the structured assessment generated by the AI agent.
"""

import enum
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import Column, String, DateTime, Enum as SQLEnum, ForeignKey, Text, Boolean
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship
import uuid

from app.database import Base

if TYPE_CHECKING:
    from app.models.session import Session
    from app.models.user import User


class PARUrgency(str, enum.Enum):
    """PAR urgency level enumeration"""
    ROUTINE = "routine"
    URGENT = "urgent"
    IMMEDIATE = "immediate"


class PAR(Base):
    """
    PAR (Preliminary Assessment Report) model.
    
    Contains the structured assessment generated by the AI agent
    after gathering patient information. Requires nurse review.
    """
    
    __tablename__ = "pars"
    
    # Primary Key
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    
    # Foreign Keys
    session_id = Column(UUID(as_uuid=True), ForeignKey("sessions.id"), nullable=False, unique=True, index=True)
    
    # PAR Content (Structured JSON)
    chief_complaint = Column(Text, nullable=False)
    symptoms = Column(JSONB, default=list, nullable=False)  # List of symptoms
    assessment = Column(Text, nullable=False)
    urgency = Column(
        SQLEnum(PARUrgency),
        default=PARUrgency.ROUTINE,
        nullable=False,
        index=True
    )
    
    # RAG Sources (for transparency)
    rag_sources = Column(JSONB, default=list, nullable=False)
    
    # Red Flags
    red_flags = Column(JSONB, default=list, nullable=False)
    has_red_flags = Column(Boolean, default=False, nullable=False, index=True)
    
    # Additional Context
    additional_notes = Column(Text, nullable=True)
    
    # Nurse Review
    reviewed = Column(Boolean, default=False, nullable=False, index=True)
    reviewed_by_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    reviewed_at = Column(DateTime, nullable=True)
    
    # Review Decision
    approved = Column(Boolean, nullable=True)  # True = approved, False = overridden
    override_reason = Column(Text, nullable=True)
    override_assessment = Column(Text, nullable=True)
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    
    # Relationships
    session = relationship("Session", back_populates="par")
    reviewed_by = relationship("User", foreign_keys=[reviewed_by_id])
    
    def __repr__(self):
        return f"<PAR(id={self.id}, urgency={self.urgency}, reviewed={self.reviewed})>"
    
    @property
    def is_reviewed(self) -> bool:
        """Check if PAR has been reviewed"""
        return self.reviewed
    
    @property
    def is_approved(self) -> bool:
        """Check if PAR was approved by nurse"""
        return self.reviewed and self.approved
    
    @property
    def is_overridden(self) -> bool:
        """Check if PAR was overridden by nurse"""
        return self.reviewed and not self.approved
    
    @property
    def requires_immediate_attention(self) -> bool:
        """Check if PAR requires immediate attention"""
        return self.urgency == PARUrgency.IMMEDIATE or self.has_red_flags
